import { mkdir, writeFile, rm, symlink, cp, lstat, readlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import YAML from "yaml";
import type { Adapter, Ctx, DbChangeProvider, Level, MediaStrategy, RepoConfig, Step } from "./types.js";
import { clampLevel } from "./config.js";
import { ddev, ddevStatus } from "./ddev.js";
import { branchExists } from "./git.js";
import { urlFor } from "./ddevconfig.js";
import { declaredDeps, missingDeps, runTool } from "./deps.js";
import { EXIT, WtError } from "./types.js";

/** §5 — level = max(framework floor, task hints, explicit), clamped by policy. */
export function inferLevel(cfg: RepoConfig, adapters: Adapter[], explicit: number | undefined, task: string | undefined): { level: Level; reasons: string[] } {
  const reasons: string[] = [];
  let l = 0;
  for (const a of adapters) { if (a.floorLevel() > l) { l = a.floorLevel(); reasons.push(`${a.id} floor=${a.floorLevel()}`); } }
  if (task) for (const [re, lv] of Object.entries(cfg.hints)) {
    if (new RegExp(re, "i").test(task) && lv > l) { l = lv; reasons.push(`task matched /${re}/ → ${lv}`); }
  }
  if (explicit !== undefined) { l = explicit; reasons.push(`explicit --level ${explicit}`); }
  const c = clampLevel(l, cfg);
  if (c !== l) reasons.push(`clamped to policy [${cfg.min_level},${cfg.max_level}] → ${c}`);
  return { level: c, reasons };
}

// ---------------------------------------------------------------------------
// Reusable step builders. planNew / planPromote / planPoolClaim compose these.
// ---------------------------------------------------------------------------

export function stepWorktreeAdd(ctx: Ctx, from: string): Step {
  const { rec, repoRoot } = ctx;
  let createdBranch = false;
  return {
    title: `git worktree add ${path.relative(repoRoot, rec.path)} (${rec.branch})`,
    async up(c) {
      const exists = await branchExists(c.run, repoRoot, rec.branch);
      createdBranch = !exists;
      const args = exists ? ["worktree", "add", rec.path, rec.branch] : ["worktree", "add", "-b", rec.branch, rec.path, from];
      await c.run("git", args, { cwd: repoRoot });
    },
    async down(c) {
      await c.run("git", ["worktree", "remove", "--force", rec.path], { cwd: repoRoot, allowFail: true });
      if (createdBranch) await c.run("git", ["branch", "-D", rec.branch], { cwd: repoRoot, allowFail: true });
    },
  };
}

export function mediaPathsOf(adapters: Adapter[]) { return [...new Set(adapters.flatMap((a) => a.mediaPaths()))]; }

/** nginx snippet: serve media locally if present, else proxy to main's URL. Zero filesystem coupling. */
function mediaProxyConf(ctx: Ctx, mediaPaths: string[]): string {
  const mainUrl = `https://${ctx.cfg.main}.${ctx.cfg.tld}`;
  return `# ddev-generated: no — managed by wt (media: proxy). Falls back to ${mainUrl} for media missing locally.
${mediaPaths.map((m) => `location ^~ /${m.replace(/^\/+/, "")}/ {
    try_files $uri @wt_media_main;
}`).join("\n")}
location @wt_media_main {
    # Inside the container, ${ctx.cfg.main}.${ctx.cfg.tld} would resolve to 127.0.0.1 (ourselves),
    # so go through the shared router by its network name and set the Host header instead.
    resolver 127.0.0.11 valid=30s;
    proxy_ssl_server_name on;
    proxy_ssl_name ${ctx.cfg.main}.${ctx.cfg.tld};
    proxy_ssl_verify off;
    proxy_set_header Host ${ctx.cfg.main}.${ctx.cfg.tld};
    proxy_pass https://ddev-router$request_uri;
}
`;
}

export function stepWriteConfig(ctx: Ctx, adapters: Adapter[]): Step {
  const { rec } = ctx;
  const written: string[] = [];
  return {
    title: "write .ddev/config.wt.local.yaml (+ env files)",
    async up(c) {
      const merged: Record<string, unknown> = {
        // Set the project name explicitly. DDEV merges config.*.yaml over config.yaml,
        // so this wins even when the repo pins `name:` in .ddev/config.yaml — verified
        // against DDEV v1.25.1 with `ddev utility configyaml`. Without it, a repo that
        // pins its name would register the worktree under *main's* project name.
        name: rec.name,
        ...Object.assign({}, ...adapters.map((a) => a.ddevOverrides(c))),
      };
      const mp = mediaPathsOf(adapters);
      if (rec.media !== "none" && mp.length) merged.upload_dirs = mp;
      const ddevDir = path.join(rec.path, ".ddev");
      await mkdir(ddevDir, { recursive: true });
      const header = `# generated by wt for worktree ${rec.name}; gitignored; do not edit\n`;
      const files: Record<string, string> = { ".ddev/config.wt.local.yaml": header + YAML.stringify(merged) };
      if (rec.media === "proxy" && mp.length) files[".ddev/nginx/wt-media.conf"] = mediaProxyConf(c, mp);
      for (const a of adapters) Object.assign(files, await a.envFiles(c));
      for (const [rel, content] of Object.entries(files)) {
        const p = path.join(rec.path, rel);
        if (!c.dryRun) { await mkdir(path.dirname(p), { recursive: true }); await writeFile(p, content); }
        if (!rec.createdFiles.includes(p)) rec.createdFiles.push(p);
        written.push(p);
      }
      c.log(`  files: ${written.map((x) => path.relative(rec.path, x)).join(", ")}`);
    },
    async down(c) { if (!c.dryRun) for (const f of written) await rm(f, { force: true }); },
  };
}

export function stepMedia(ctx: Ctx, adapters: Adapter[], mode: MediaStrategy = ctx.rec.media): Step | null {
  const { rec, repoRoot } = ctx;
  const mp = mediaPathsOf(adapters);
  if (!mp.length || mode === "none" || mode === "proxy") return null; // proxy is handled by the nginx snippet
  return {
    title: `media: ${mode} ${mp.join(", ")}`,
    async up(c) {
      for (const m of mp) {
        const src = path.join(repoRoot, m), dst = path.join(rec.path, m);
        if (!existsSync(src)) { c.log(`  skip ${m} (not in main)`); continue; }
        if (c.dryRun) continue;
        await rm(dst, { recursive: true, force: true });
        await mkdir(path.dirname(dst), { recursive: true });
        if (mode === "symlink") await symlink(path.relative(path.dirname(dst), src), dst);
        else await copyTree(c, src, dst);
      }
    },
    async down(c) { if (!c.dryRun) for (const m of mp) await rm(path.join(rec.path, m), { recursive: true, force: true }); },
    optional: true, // a failed media sync should not tear down a freshly cloned environment
  };
}

/** APFS clone on macOS (`cp -c`, copy-on-write, ~free), plain recursive copy elsewhere. */
async function copyTree(c: Ctx, src: string, dst: string) {
  if (process.platform === "darwin") {
    const r = await c.run("cp", ["-cR", src, dst], { allowFail: true });
    if (r.exitCode === 0) return;
  }
  await cp(src, dst, { recursive: true, force: true, dereference: false });
}

export function stepDbClone(ctx: Ctx): Step | null {
  const { rec, cfg, repoRoot } = ctx;
  if (rec.db === "seedfile") {
    const seed = path.join(repoRoot, cfg.seed.file);
    return {
      title: `db: seed file ${cfg.seed.file}`,
      async up(c) {
        if (!existsSync(seed) && !c.dryRun) throw new WtError(EXIT.GENERIC, `seed file missing: ${seed}`, "wt db seed   (refreshes it from main / ddev pull)");
      },
    };
  }
  if (rec.db !== "snapshot" && rec.db !== "dump") return null;
  return {
    title: `db: ${rec.db} from ${cfg.main}`,
    async up(c) {
      const st = await ddevStatus(c.run, cfg.main);
      if (st !== "running" && !c.dryRun) throw new WtError(EXIT.MAIN_NOT_RUNNING, `main project "${cfg.main}" is not running (status: ${st ?? "unknown"})`, `run: ddev start ${cfg.main}`);
      if (rec.db === "snapshot") {
        const snap = `wt-${rec.name}`;
        await ddev.snapshot(c.run, repoRoot, snap);
        const from = path.join(repoRoot, ".ddev", "db_snapshots"), to = path.join(rec.path, ".ddev", "db_snapshots");
        if (!c.dryRun) {
          if (!existsSync(from)) throw new WtError(EXIT.GENERIC, `snapshot dir missing: ${from}`, "did `ddev snapshot` succeed in main?");
          await mkdir(to, { recursive: true });
          // Copy only this snapshot. DDEV writes a file (`<name>-<dbtype>_<version>.gz`),
          // older versions wrote a directory — match on the first path segment so both work.
          await cp(from, to, { recursive: true, filter: (p) => p === from || path.relative(from, p).split(path.sep)[0].startsWith(snap) });
        }
        rec.snapshots.push(snap);
      } else {
        const file = path.join(rec.path, ".ddev", "wt-main.sql");
        await ddev.exportDb(c.run, repoRoot, file);
        rec.createdFiles.push(file);
      }
    },
  };
}

export function stepStart(ctx: Ctx, adapters: Adapter[]): Step {
  const { rec, cfg } = ctx;
  return {
    title: `ddev start → ${rec.url || urlFor(rec.name, cfg.tld)}`,
    async up(c) {
      await ddev.start(c.run, rec.path);
      if (rec.db === "snapshot" && rec.snapshots[0]) await ddev.snapshotRestore(c.run, rec.path, rec.snapshots[0]);
      if (rec.db === "dump") await ddev.importDb(c.run, rec.path, path.join(rec.path, ".ddev", "wt-main.sql"));
      if (rec.db === "seedfile") await ddev.importDb(c.run, rec.path, path.join(ctx.repoRoot, cfg.seed.file));
      // post-start hooks ran before the restore replaced the DB → run them once more
      if (rec.db !== "none" && rec.db !== "fresh") await ddev.start(c.run, rec.path);
      for (const a of adapters) await a.postStart(c);
      rec.prevUrl = rec.url;
    },
    async down(c) { await ddev.delete(c.run, rec.name); },
  };
}

/**
 * `git worktree add` gives you exactly what git tracks — which is not a runnable
 * checkout. Gitignored-but-required directories are missing, and at level 0/1 nothing
 * else ever writes an env file. Both failures surface far from their cause (an artisan
 * call dying inside the container), so fix them at creation.
 */
export function stepPrepareTree(ctx: Ctx, adapters: Adapter[]): Step | null {
  const { rec, repoRoot } = ctx;
  const dirs = [...new Set(adapters.flatMap((a) => a.requiredDirs?.() ?? []))];
  const shared = rec.level < 2 ? [...new Set(adapters.flatMap((a) => a.sharedFiles?.() ?? []))] : [];
  if (!dirs.length && !shared.length) return null;
  return {
    title: `prepare tree (${[...dirs, ...shared].join(", ")})`,
    async up(c) {
      if (c.dryRun) return;
      for (const d of dirs) await mkdir(path.join(rec.path, d), { recursive: true });
      for (const f of shared) {
        const src = path.join(repoRoot, f), dst = path.join(rec.path, f);
        if (!existsSync(src)) { c.log(`  skip ${f} (not in main)`); continue; }
        if (existsSync(dst)) continue;
        await cp(src, dst);
        if (!rec.createdFiles.includes(dst)) rec.createdFiles.push(dst);
      }
    },
    optional: true,
  };
}

/**
 * Level 0/1 tooling runs in *main's* container, at the worktree's path under the
 * project mount. `git worktree add` returns as soon as the host checkout is written,
 * but on a Mutagen-synced project (macOS/Windows) the container cannot see those files
 * for another few seconds — long enough that the very next `wt composer …` fails with
 * "no such file or directory". Wait for the tree to land instead of handing the agent
 * a confusing error.
 */
export function stepAwaitContainerSync(ctx: Ctx, adapters: Adapter[] = [], timeoutMs = 120_000): Step {
  const { rec, repoRoot } = ctx;
  const inContainer = path.posix.join("/var/www/html", path.relative(repoRoot, rec.path));
  // `.git` alone is not enough: it is one small file and lands before the rest of the
  // checkout, which produced "Could not open input file: artisan" seconds after wt
  // reported the worktree ready. Wait for each framework's own root file too.
  const markers = [".git", ...new Set(adapters.map((a) => a.treeMarker?.()).filter((m): m is string => !!m))];
  return {
    title: `wait for ${inContainer} to sync into main's web container`,
    async up(c) {
      if (c.dryRun) return;
      const deadline = Date.now() + timeoutMs;
      let waited = false;
      for (;;) {
        const r = await c.run("ddev", ["exec", "--dir", inContainer, "sh", "-c", markers.map((m) => `test -e '${m}'`).join(" && ")], { cwd: repoRoot, allowFail: true });
        if (r.exitCode === 0) { if (waited) c.log("  synced"); return; }
        if (Date.now() > deadline) throw new Error(`still not visible in the container after ${Math.round(timeoutMs / 1000)}s — is main running, and is this project Mutagen-synced?`);
        waited = true;
        await new Promise((res) => setTimeout(res, 2000));
      }
    },
    // A failure here means tooling will be slow to work, not that the worktree is broken.
    optional: true,
  };
}

/** Opt-in: `wt new --install`. Costs minutes on a large repo, so it is never the default. */
export function stepInstallDeps(ctx: Ctx, adapters: Adapter[]): Step | null {
  const deps = declaredDeps(adapters);
  if (!deps.length) return null;
  return {
    title: `install dependencies (${deps.map((d) => d.marker.split("/")[0]).join(", ")})`,
    async up(c) {
      if (c.dryRun) return;
      for (const d of missingDeps(c.rec, adapters)) {
        c.log(`  ${d.tool} ${d.args.join(" ")}`);
        const r = await runTool(c.run, c.repoRoot, c.rec, d.tool, d.args);
        if (r.exitCode !== 0) throw new Error(`${d.tool} ${d.args.join(" ")} failed: ${(r.stderr || r.stdout).split("\n").filter(Boolean).slice(-2).join(" ")}`);
      }
    },
    // The worktree is still usable without them; the agent just has to run the install itself.
    optional: true,
  };
}

export function stepBaseline(ctx: Ctx, providers: DbChangeProvider[]): Step {
  const { rec, cfg } = ctx;
  return {
    title: `db change-tracking baseline (${providers.map((p) => p.id).join(", ")})`,
    async up(c) {
      for (const p of providers) rec.baseline = await p.baseline(c);
      const changes = path.join(rec.path, cfg.db.changes_dir);
      if (!c.dryRun) { await mkdir(changes, { recursive: true }); if (!existsSync(path.join(changes, ".gitkeep"))) await writeFile(path.join(changes, ".gitkeep"), ""); }
    },
  };
}

/** Steps that turn an existing worktree dir into a running level-2+ environment. */
export function stepsEnvironment(ctx: Ctx, adapters: Adapter[], providers: DbChangeProvider[], start: boolean): Step[] {
  const steps: Step[] = [stepWriteConfig(ctx, adapters)];
  const m = stepMedia(ctx, adapters); if (m) steps.push(m);
  if (!start) return steps;
  const d = stepDbClone(ctx); if (d) steps.push(d);
  steps.push(stepStart(ctx, adapters), stepBaseline(ctx, providers));
  return steps;
}

// ---------------------------------------------------------------------------

export function planNew(ctx: Ctx, adapters: Adapter[], providers: DbChangeProvider[], opts: { from: string; start: boolean; install?: boolean }): Step[] {
  const { rec } = ctx;
  const steps: Step[] = [stepWorktreeAdd(ctx, opts.from)];
  const prep = stepPrepareTree(ctx, adapters); if (prep) steps.push(prep);
  const install = opts.install ? stepInstallDeps(ctx, adapters) : null;
  if (rec.level === 0) return steps;
  if (rec.level === 1) {
    steps.push({ title: "level 1: no containers; `wt npm|composer|artisan|wp <name> …` run in main's web container", async up() {} });
    steps.push(stepAwaitContainerSync(ctx, adapters));
    // after the sync wait: the container has to see the tree before it can install into it
    if (install) steps.push(install);
    return steps;
  }
  const env = stepsEnvironment(ctx, adapters, providers, opts.start);
  // after start: `ddev composer` needs the worktree's own containers up
  return install ? [...steps, ...env, install] : [...steps, ...env];
}

/** In-place level change. Supported: 0/1→2+, 2↔3 (media swap), any→media mode change. */
export function planPromote(ctx: Ctx, adapters: Adapter[], providers: DbChangeProvider[], to: Level, media?: MediaStrategy): Step[] {
  const { rec } = ctx;
  const fromLevel = rec.level;
  const steps: Step[] = [];
  if (to === 4 || fromLevel === 4) throw new WtError(EXIT.GENERIC, "level 4 (clean) cannot be promoted to/from in place — recreate with `wt new --level 4`");
  if (to < 2 && fromLevel >= 2) throw new WtError(EXIT.GENERIC, "demoting below level 2 would delete the environment — use `wt destroy` + `wt new`");

  const targetMedia: MediaStrategy = media ?? (to >= 3 ? "copy" : to === 2 ? (rec.media === "copy" ? "symlink" : rec.media) : rec.media);

  if (fromLevel < 2 && to >= 2) {
    rec.level = to; rec.media = targetMedia; rec.db = ctx.cfg.defaults.db; rec.url = urlFor(rec.name, ctx.cfg.tld);
    return stepsEnvironment(ctx, adapters, providers, true);
  }

  // level ≥ 2 already: only media may change
  if (targetMedia !== rec.media) {
    const prev = rec.media;
    steps.push({
      title: `media: ${prev} → ${targetMedia}`,
      async up(c) {
        rec.media = targetMedia;
        if (prev === "proxy" || targetMedia === "proxy") await stepWriteConfig(c, adapters).up(c); // (re)write nginx snippet + config
        if (prev === "proxy" && targetMedia !== "proxy" && !c.dryRun) await rm(path.join(rec.path, ".ddev", "nginx", "wt-media.conf"), { force: true });
        const m = stepMedia(c, adapters, targetMedia);
        if (m) await m.up(c);
        else if (targetMedia === "proxy" || targetMedia === "none") for (const p of mediaPathsOf(adapters)) {
          const dst = path.join(rec.path, p);
          if (!c.dryRun && existsSync(dst)) { const st = await lstat(dst); if (st.isSymbolicLink() || targetMedia === "none") await rm(dst, { recursive: true, force: true }); }
        }
        if (prev === "proxy" || targetMedia === "proxy") await c.run("ddev", ["restart"], { cwd: rec.path });
      },
      async down() { rec.media = prev; },
    });
  }
  steps.push({ title: `level ${fromLevel} → ${to}`, async up() { rec.level = to; } });
  return steps;
}

/** Claim a warm-pool entry: rename dir/project, switch branch, rewrite URLs. Much faster than a fresh clone. */
export function planPoolClaim(ctx: Ctx, adapters: Adapter[], providers: DbChangeProvider[], poolRec: { name: string; path: string; url: string; snapshots: string[] }, from: string): Step[] {
  const { rec, repoRoot } = ctx;
  // DDEV names the database volume after the project, so `ddev delete` below takes the
  // pooled database with it — the very thing the pool exists to have ready. Snapshot it
  // first: the file lands in <path>/.ddev/db_snapshots, travels with `git worktree move`,
  // and is restored into the renamed project after it starts. Same mechanism as
  // stepDbClone, which is verified against real DDEV.
  const claimSnap = `wt-claim-${rec.name}`;
  return [
    {
      title: `claim pool entry ${poolRec.name} → ${rec.name}`,
      async up(c) {
        await ddev.snapshot(c.run, poolRec.path, claimSnap);
        await ddev.stop(c.run, poolRec.name);
        await ddev.delete(c.run, poolRec.name); // drops the registry entry for the old name; containers and the db volume are recreated under the new one
        await c.run("git", ["worktree", "move", poolRec.path, rec.path], { cwd: repoRoot });
        const exists = await branchExists(c.run, repoRoot, rec.branch);
        const poolBranch = (await c.run("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd: rec.path, allowFail: true })).stdout.trim();
        await c.run("git", exists ? ["checkout", rec.branch] : ["checkout", "-b", rec.branch, from], { cwd: rec.path });
        if (poolBranch.startsWith("wt/")) await c.run("git", ["branch", "-D", poolBranch], { cwd: repoRoot, allowFail: true });
        rec.prevUrl = poolRec.url; // DB still references the pool hostname; adapters rewrite prevUrl → url
        rec.snapshots = [];
        // The renamed project must not reuse router/cert config generated for the old name (learned from workspace-manager).
        if (!c.dryRun) await rm(path.join(rec.path, ".ddev", "traefik"), { recursive: true, force: true });
      },
      async down(c) {
        // Moving back is pointless: `up` deleted the pool project irreversibly and the
        // entry has already been struck from the manifest, so there is no pool entry to
        // restore. Clear the debris instead of leaving a half-renamed worktree that makes
        // the next claim fail with "path exists".
        for (const p of [rec.path, poolRec.path]) {
          await c.run("git", ["worktree", "remove", "--force", p], { cwd: repoRoot, allowFail: true });
          if (!c.dryRun) await rm(p, { recursive: true, force: true });
        }
        await c.run("git", ["worktree", "prune"], { cwd: repoRoot, allowFail: true });
      },
    },
    stepWriteConfig(ctx, adapters),
    {
      title: `ddev start → ${rec.url} (URL fixup from ${poolRec.url})`,
      async up(c) {
        await ddev.start(c.run, rec.path);
        await ddev.snapshotRestore(c.run, rec.path, claimSnap);
        // post-start hooks ran against the empty database the new volume started with,
        // so run them again now the pooled data is back — this is what rewrites
        // poolRec.url to rec.url
        await ddev.start(c.run, rec.path);
        for (const a of adapters) await a.postStart(c);
        await ddev.snapshot(c.run, rec.path, `wt-${rec.name}`); rec.snapshots.push(`wt-${rec.name}`);
        rec.prevUrl = rec.url;
      },
      async down(c) { await ddev.delete(c.run, rec.name); },
    },
    stepBaseline(ctx, providers),
  ];
}

export function planDestroy(ctx: Ctx, keepBranch: boolean): Step[] {
  const { rec, repoRoot } = ctx;
  return [
    { title: `ddev delete ${rec.name} (snapshots too)`, async up(c) { if (rec.level >= 2) await ddev.delete(c.run, rec.name); } },
    { title: "remove generated files", async up(c) { if (!c.dryRun) for (const f of rec.createdFiles) await rm(f, { force: true }).catch(() => {}); } },
    { title: "remove baseline", async up(c) { if (!c.dryRun) await rm(path.join(repoRoot, ".wt", "baseline", rec.name), { recursive: true, force: true }); } },
    {
      // Destroy has to be idempotent. A worktree whose directory is already gone — removed by
      // hand, or by an earlier destroy that died after this step — would otherwise fail here,
      // and because the caller only strikes the manifest entry once every step succeeds, the
      // record would survive and keep counting against max_concurrent forever.
      title: `git worktree remove ${path.relative(repoRoot, rec.path)}`,
      async up(c) {
        const alreadyGone = !c.dryRun && !existsSync(rec.path);
        await c.run("git", ["worktree", "remove", "--force", rec.path], { cwd: repoRoot, allowFail: alreadyGone });
        // Drops the stale .git/worktrees admin entry a vanished directory leaves behind.
        if (alreadyGone) await c.run("git", ["worktree", "prune"], { cwd: repoRoot, allowFail: true });
      },
    },
    ...(keepBranch ? [] : [{ title: `git branch -D ${rec.branch}`, async up(c: Ctx) { await c.run("git", ["branch", "-D", rec.branch], { cwd: repoRoot, allowFail: true }); } }]),
  ];
}

export { readlink };
