import { existsSync } from "node:fs";
import path from "node:path";
import type { Adapter } from "../core/types.js";
import { ddev } from "../core/ddev.js";

/**
 * Drupal adapter. Recipe borrowed from workspace-manager: files under web/sites/default/files,
 * DDEV's settings.ddev.php carries the DB host (regenerated by `ddev start`, so nothing to patch
 * when `name:` is omitted), and after a DB import run drush cr → cim → deploy:hook.
 */
export const drupal: Adapter = {
  id: "drupal",
  floorLevel: () => 2, // config/state in DB; a hostname is baked into some caches — isolate by default
  async detect(root) {
    return ["web/core/lib/Drupal.php", "docroot/core/lib/Drupal.php", "core/lib/Drupal.php"].some((p) => existsSync(path.join(root, p)));
  },
  mediaPaths: () => ["web/sites/default/files"],
  defaultChangeProviders: () => ["snapshot-diff"],

  ddevOverrides(ctx) {
    return {
      type: "drupal",
      upload_dirs: ["web/sites/default/files"],
      hooks: { "post-start": [{ exec: "drush cr || true" }] },
      web_environment: [`WT_WORKTREE=${ctx.rec.name}`],
    };
  },

  async envFiles() { return {}; },

  async postStart(ctx) {
    if (ctx.rec.db === "none" || ctx.rec.db === "fresh") return;
    for (const cmd of [["drush", "cr"], ["drush", "cim", "-y"], ["drush", "cr"], ["drush", "deploy:hook", "-y"], ["drush", "cr"]]) {
      const r = await ddev.exec(ctx.run, ctx.rec.path, cmd).catch((e: Error) => ({ stdout: "", stderr: e.message, exitCode: 1 }));
      if (r.exitCode) ctx.log(`  warning: ${cmd.join(" ")} failed (continuing): ${r.stderr.split("\n")[0]}`);
    }
    if (ctx.rec.level >= 2) await ddev.snapshot(ctx.run, ctx.rec.path, "wt-pre-task");
  },

  async healthCheck(ctx) {
    const r = await ctx.run("curl", ["-ksfo", "/dev/null", "-w", "%{http_code}", ctx.rec.url], { allowFail: true });
    return { ok: /^[23]/.test(r.stdout.trim()), detail: `HTTP ${r.stdout.trim() || "n/a"} ${ctx.rec.url}` };
  },
};
