import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import type { Adapter } from "../core/types.js";

export const react: Adapter = {
  id: "react",
  floorLevel: () => 1, // all tooling runs via `ddev npm`; level 1 borrows main's web container, level 2 gets its own project + URL
  async detect(root) {
    const p = path.join(root, "package.json");
    if (!existsSync(p)) return false;
    const pkg = JSON.parse(await readFile(p, "utf8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    return ["react", "next", "vite"].some((d) => d in deps);
  },
  mediaPaths: () => [],
  defaultChangeProviders: () => [],

  ddevOverrides(ctx) {
    // Level ≥ 2: run the dev server inside the web container and expose it on the project hostname
    // through the shared router — no host ports, no collisions with other agents.
    return {
      type: "generic",
      webserver_type: "generic",
      web_extra_exposed_ports: [{ name: "vite", container_port: 5173, http_port: 80, https_port: 443 }],
      web_extra_daemons: [{ name: "vite", command: "npm run dev -- --host 0.0.0.0 --port 5173", directory: "/var/www/html" }],
      hooks: { "post-start": [{ exec: "[ -d node_modules ] || npm ci" }] },
    };
  },

  async envFiles(ctx) {
    const api = ctx.cfg.react.pair_with ? `https://${path.basename(ctx.cfg.react.pair_with)}-${ctx.rec.name}.${ctx.cfg.tld}` : "";
    return { ".env.local": `# generated by wt (worktree: ${ctx.rec.name})\nVITE_APP_URL=${ctx.rec.url}\n${api ? `VITE_API_URL=${api}\n` : ""}` };
  },

  async postStart() { /* nothing */ },

  async healthCheck(ctx) {
    if (ctx.rec.level < 2) return { ok: true, detail: "level <2: no URL; run `wt npm <name> test` / `wt npm <name> run build` (executes in main's web container)" };
    const r = await ctx.run("curl", ["-ksfo", "/dev/null", "-w", "%{http_code}", ctx.rec.url], { allowFail: true });
    return { ok: /^[23]/.test(r.stdout.trim()), detail: `HTTP ${r.stdout.trim() || "n/a"} ${ctx.rec.url}` };
  },
};
