import { existsSync } from "node:fs";
import path from "node:path";
import type { Adapter, Ctx } from "../core/types.js";
import { ddev } from "../core/ddev.js";

export const wordpress: Adapter = {
  id: "wordpress",
  floorLevel: () => 2, // site URL lives in the DB → never share a DB across hostnames
  async detect(root) {
    return ["wp-config.php", "wp-content", "web/wp-config.php", "public/wp-config.php"].some((p) => existsSync(path.join(root, p)));
  },
  mediaPaths: () => ["wp-content/uploads"],
  defaultChangeProviders: () => ["wp-changeset", "snapshot-diff"],

  ddevOverrides(ctx) {
    const mainUrl = ctx.rec.prevUrl && ctx.rec.prevUrl !== ctx.rec.url ? ctx.rec.prevUrl : `https://${ctx.cfg.main}.${ctx.cfg.tld}`;
    const extra = ctx.cfg.wordpress.search_replace_extra.map((s) => `wp search-replace '${s}' '${s}' --all-tables --skip-columns=guid`);
    return {
      type: "wordpress",
      upload_dirs: ["wp-content/uploads"],
      hooks: {
        "post-start": [
          // idempotent: re-running replace of new→new is a no-op
          { exec: `wp search-replace '${mainUrl}' '${ctx.rec.url}' --all-tables --precise --recurse-objects --skip-columns=guid || true` },
          { exec: "wp option update blog_public 0 || true" },
          { exec: "wp cache flush || true; wp rewrite flush --hard || true" },
          ...extra.map((exec) => ({ exec })),
        ],
      },
    };
  },

  async envFiles(ctx) {
    // Belt-and-braces URL pinning for plugins that ignore the DB; included by wp-config.php via shim.
    const php = `<?php
// Generated by wt — do not commit. Worktree: ${ctx.rec.name}
define('WP_HOME', '${ctx.rec.url}');
define('WP_SITEURL', '${ctx.rec.url}');
define('WP_ENVIRONMENT_TYPE', 'development');
define('WT_WORKTREE', '${ctx.rec.name}');
`;
    return { "wp-config-wt.php": php };
  },

  async postStart(ctx) {
    // Hooks already did search-replace; verify no main hostname leaked.
    const r = await ddev.exec(ctx.run, ctx.rec.path, ["wp", "db", "query", `SELECT COUNT(*) FROM wp_options WHERE option_value LIKE '%${ctx.cfg.main}.${ctx.cfg.tld}%'`]);
    if (/^\s*[1-9]/m.test(r.stdout.split("\n").pop() ?? "")) ctx.log("warning: main hostname still present in wp_options — run `wt doctor`");
  },

  async healthCheck(ctx) {
    const r = await ctx.run("curl", ["-ksfo", "/dev/null", "-w", "%{http_code}", ctx.rec.url], { allowFail: true });
    return { ok: r.stdout.trim().startsWith("2") || r.stdout.trim().startsWith("3"), detail: `HTTP ${r.stdout.trim() || "n/a"} ${ctx.rec.url}` };
  },
};
